general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# 1. Dim Backlight (2.5 min)
listener {
    timeout = 150
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r
}

# 2. Keyboard Backlight (2.5 min)
listener { 
    timeout = 150
    on-timeout = brightnessctl -sd rgb:kbd_backlight set 0
    on-resume = brightnessctl -rd rgb:kbd_backlight
}

# 3. Lock Session (5 min)
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# 4. Turn off Display (5.5 min)
listener {
    timeout = 330
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on && brightnessctl -r
}

# 5. Suspend PC (30 min)
listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
