{ ... }:
{
    imports = [
        ./alacritty.nix
        ./bash.nix
        ./bat.nix
        ./btop.nix
        ./git.nix
        ./godot.nix
        ./heroic.nix
        ./hyprland
        ./librewolf.nix
        ./neovim/neovim.nix
        ./pcmanfm.nix
        ./rofi/rofi.nix
        ./swaync/swaync.nix
        ./telegram.nix
        ./tree.nix
        ./waybar
        ./kitty/kitty.nix
        ./utilities.nix
        ./nemo.nix
        ./amberol.nix
        ./prismlauncher.nix
        ./gtk.nix
        ./vesktop.nix
        ./art.nix
        ./libreoffice.nix
    ];
}
